config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'
  get 'events/index'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'events/show'
  post 'users/new'
  post 'events/index'
  get 'sessions/new'
  post  'sessions/create'
  delete  'sessions/destroy'
  get 'events/new'

  resources :event_invitations

  resources :sessions, only: [:create, :new, :destroy]
  get '/signup', to: 'users#new'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'

  resources :users, only: [:new, :create, :show, :index]
  resources :events, only: [:new, :create, :index, :show]
  resources :registrations, only: [:create]
  resources :sessions, only: [:create, :destroy]
  root to: "users#new"
  
  resources :events do
    post 'attend', on: :member
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_invitations
  has_many :attendees, through: :event_invitations, foreign_key: :attendee_id, source: :user

  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'

  scope :past, -> { where('date < ?', Date.today) }
  scope :upcoming, -> { where('date >= ?', Date.today) }
end

app/models/event_invitation.rb
class EventInvitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: { scope: :name, case_sensitive: true }

  has_many :event_invitations
  has_many :events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy

  has_many :attended_events, through: :event_invitations, foreign_key: :attendee_id, source: :event, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token

  # This method checks if we have a user signed in
  def login_required
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  helper_method :logged_in?

  # This method gives us details about our user
  def current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
      @current_user
    else
      false
    end
  end

  helper_method :current_user

  def current_event
    if session[:event_id]
      @current_event = Event.find(session[:event_id])
      @current_event
    else
      false
    end
  end

  helper_method :current_event
end

app/controllers/event_invitations_controller.rb
class EventInvitationsController < ApplicationController
  def new
    @event_invitation = EventInvitation.new
  end

  def index
    @event_invitation = EventInvitation.new
  end

  def attend
    @event = Event.find_by(params[:event_id])
    @event.attendees << @user
    @event.save
  end

  def show
    @user = User.where.not(id: :current_user.id)
    @users = User.all
  end

  def create
    @event_invitation = EventInvitation.new(event_registration_params)

    redirect_to users_show_path if @event_invitation.save
  end

  def invitation
    @event = Event.find_by(id: params[:event_id])
    @user = User.find_by(id: session[:user_id])
    @event.attendees << @user
    @event.save
  end

  private

  def set_event_registration
    @attendee = Attendee.find(params[:id])
  end

  def event_registration_params
    params.require(:event_invitation).permit(:user_id, :event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
    @event = current_user.events
    @user = User.find_by(id: session[:user_id])
    @attended_events = @user.attended_events.all
    @attendeename = @user.name
  end

  def attend
    @user = User.find_by(id: session[:user_id])
    @event = Event.find_by(params[:event_id])
    @event.attendees << @user
    @event.save
  end

  def new
    @event = Event.new
    @user = current_user
  end

  def show
    @event = Event.find_by(params[:event_id])
    @events = Event.all
    @user = User.find_by(name: params[:user_name])
  end

  def create
    @user = User.find_by(id: session[:user_id])
    @event = @user.events.build(event_params)
    if @event.save
      redirect_to users_show_path
    else
      render :new
    end
  end

  def invitation
    @event = Event.find_by(params[:event_id])
    @events = Event.all
    @attendees = @event.attendees
    @user = User.find_by(params[:name])
    @event_invitation = EventInvitation.new(user_id: @user.id, event_id: @event.id)
    @event_invitation.save
  end

  def update
    @event = Event.find_by(params[:event_id])
    @events = Event.all
    @user = User.find_by(id: params[:user_id])
    @users = User.all
  end

  private

  def event_params
    params.require(:event).permit(:location, :date)
  end

  def attendee_params
    params.require(:event).permit(:attendes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(params[:name])
    if @user
      session[:name] = @user.name
      session[:user_id] = @user.id
      redirect_to new_event_url
    else
      redirect_to sessions_create_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_new_path
  end

  private

  def login(user)
    session[:user_id] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @users = User.all
    @event = Event.find_by(params[:id])
    @events = Event.all
  end

  def show
    @user = User.where.not(id: current_user.id)
    @users = @user.all
    @event = Event.find_by(params[:id])
    @events = Event.all
    @event_invitation = EventInvitation.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to events_new_path
      if params[:remember_name]
        cookies[:user_name] = @user.name
      else
        cookies.delete(:user_name)
      end
    else
      redirect_to users_new_path
      flash.now[:notice] = "User not registered"
    end
  end

  def authenticate
    env["warden"].authenticate!
  end

  def invite
    @event = Event.find_by(id: params[:event_id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :id)
  end

  def name
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_invitations/index.html.erb
<h1>"Hello World"</h1>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
    <div class="field">
        <div class="control">
        <%= f.label :Event_description, class: "label" %>
        <%= f.text_field :location, class: "textarea", required: true %>
        </div>
    </div>

    <div class="field">
    <div class="control">
    <%= f.datetime_field :date, class: "input is-info", placeholder: "Date" %>
    </div>
    </div>

    <div class="field">
    <div class="control">
      <%= f.submit "Submit", class: "button s-large is-fullwidth btn btn-large btn-primary" %>
    </div>
  </div>
<% end %>

app/views/events/_invitation-form.html.erb
<%= form_with model: @event, url: events_invitation_path do |f| %>
    <%= f.collection_select :user_id, @user.without([current_user]),:id,:name, include_blank: true  %>                
    <%= f.submit "Invite", class: "button is-primary is-large is-fullwidth btn btn-large btn-primary" %>
<% end %>

app/views/events/_list.html.erb
<%= "Attendees: " %>
<% @attendees.each do | attendee | %>
  <tr>
    <td><%= attendee.name %></td></br>
  </tr>
<% end %>

app/views/events/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

    <li class="nav-item">
      <% if logged_in? %>
        <div class="p-2 "><span>Welcome, <%= current_user.name %>!</span></div>
      <% else %>
      <div class="p-2 "><%= link_to "Log in", users_new_path %></div>
      <% end %>
    </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "My events", users_show_path %></div>
      </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "Attendees", events_show_path %></div>
      </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "Index", events_index_path %></div>
      </li>

      <li class="nav-item">
        <div class="p-2 "><%= link_to "Create", new_event_url %></div>
      </li>

      <li class="nav-item">
      <% if logged_in? %>
      <div class="p-2 "><%= link_to "Log out", logout_path %></div>
      <% end %>
    </li>
    </ul>
  </div>
</nav>

app/views/events/_previous.html.erb
<% @events.past.each do |event| %>
    <tr>
        <td><%= link_to event.location, event_path(event) %></td></br>
        <td><%= event.date %></td></br>
        <%= button_to 'Attend', attend_event_path(@event), method: :post, confirm: 'really?' %></br>
    </tr>   
  <% end %>

app/views/events/_upcoming.html.erb
<% @events.upcoming.each do |event| %>
    <tr>
        <td><%=link_to event.location, event_path(event) %></td></br>
        <td><%= event.date %></td></br>
    </tr>   
  <% end %>

app/views/events/index.html.erb
<% provide(:title, @user.name) %>
<%= render 'navbar', user: @user, event: @event %>
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <% if !logged_in? %>
      <%= link_to "Log in", users_new_path %>
    <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">All the Events</h2>
        <% @events.each do |event| %>
            <tr>
              <td><%= link_to event.location, event_path(event) %></td></br>
              <td><%= event.date %></td></br>
              <%= button_to 'Attend', attend_event_path(@event), method: :post, confirm: 'really?', class: "button s-large is-fullwidth btn btn-large btn-primary" %></br>
            </tr>
        <% end %>
      </div>
    </div>
  </div>
</div>



<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Previous Events</h2>
        
        <%= render 'previous', user: @user, event: @event %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Upcoming Events</h2>
        <%= render 'upcoming', user: @user, event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/invitation.html.erb
<%= render 'navbar', user: @user, event: @event %>


<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <h2 class="title is-2 is-spaced has-text-centered">My Events</h2>    
      <% if current_user.events.empty? %>
        <span>You haven't created any event yet,</span>
        <%= link_to "Create one!", new_event_url %>
      <% else %>
        <% @events.each do |event| %>
          <tr>
            <% if event.creator_id == session[:user_id] %>
              <td><%= link_to event.location, event_path(event) %></td></br>
              <td><%= event.date %></td></br>
              <% unless event.attendees.empty? %>
              <td><%= event.attendees.name %></td></br>
              <% end %>
            <% end %>
          </tr>   
        <% end %>
      <% end %>
     
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <h3 class="title is-2 is-spaced has-text-centered">Attendees List</h3>
        <% if @event.nil? %>
          <span>Nobody has confirmed yet, be the first one!</span>
        <% else %>
          <span>Number of attendees: <%= User.find(@event.attendees.map { |enr| enr.id }).count %></span></br>
          <%= render 'list', event: @event %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'navbar', user: @user, event: @event %>


<h1>"Create your events here"</h1>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render 'navbar', user: @user, event: @event %>
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <% if !logged_in? %>
      <%= link_to "Log in", users_new_path %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <h2 class="title is-2 is-spaced has-text-centered">Events</h2>
      <% if current_user.events.nil? %>
        <span>There aren't any created events yet,</span>
        <%= link_to "Create one!", new_event_url %>
      <% else %>
        <% @events.each do |event| %>
          <tr>
              <td><%= event.location %></td></br>
              <td><%= event.date %></td></br>
              <span>Event created by: </span>
              <td><%= event.creator.name %></td></br>
              <% unless event.attendees.empty? %>
              <span>Attendees: </span>
              <td><%= event.attendees.name %></td></br>
              <% end %>
          </tr>   
        <% end %>
      <% end %>      
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">

  <h3 class="title is-2 is-spaced has-text-centered">Attendees List</h3>

  <% if @event.nil? %>
  <span>Nobody has confirmed yet, be the first one!</span>
<% else %>
  <span>Number of attendees: <%= User.find(@event.attendees.map { |enr| enr.id }).count %></span></br>
  <% unless @attendees.nil? %>
    <%= render 'list', event: @event %>
  <% end %>
<% end %>

</div>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  Hiya, <%= current_user.name %>! You're looking mighty fine today!
  <%=link_to “Log Out”, logout_path %>
<% else %>
  <%= link_to “Log In”, login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="container justify-content-md-center">
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
                <div class="p-5 col-lg ml-auto mr-auto">
                <div>
                    <div class="p-2">
                    <h2 class="title is-2 is-spaced has-text-centered">Sign Up</h2>
                    </div>

                <div class="col-lg">
                    <div class="span6 offset3 pt-4 pb-4">
                    <%= form_with(model: user, local: true) do |f| %>
                      <div class="field">
                        <div class="control">
                        
                        <div class="p-1"><%= f.label :name, class: "label" %></div>
                        <div class="p-1"><%= f.text_field :name, class: "input", autofocus: true, required: true %></div>
                        <div class="p-1"><%= f.submit "Sign Up", class: "button is-primary is-large is-fullwidth btn btn-large btn-primary" %></div>
                        </div>
                      </div>
      
                    <% end %>
                    </div>
                </div>
                </div>

                <div class="col-lg ml-auto mr-auto">
                    <div class="">
                      <%= "Already have an account? " %>
                      <%= link_to "Log In", login_url %>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>

app/views/users/_invitation-form.html.erb
<%= form_with model: @event, url: events_invitation_path do |f| %>
    <%= f.collection_select :user_id, @user.without([current_user]),:id,:name, include_blank: true  %>                
    <%= f.submit "Invite", class: "button is-primary is-large is-fullwidth btn btn-large btn-primary" %>
<% end %>

app/views/users/_list.html.erb
<%= "Attendees: " %></br>
<% @event.attendees.each do | attendee | %>
  <tr>
    <td><%= attendee.name %></td></br>
  </tr>
<% end %>

app/views/users/_login.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

      <li class="nav-item">
          <div class="p-2 "><%= link_to "Log In", login_url %></div>
      </li>

    </ul>
  </div>
</nav>

<h2 class="title is-2 is-spaced has-text-centered">Sign In</h2>
        
          <div class="row">
            <div class="span6 offset3">
              <%= form_for(:session, url: sessions_path) do |f| %>

                <%= f.label :name %>
                <%= f.text_field :name, class: "input", required: true %>

                <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
              <% end %>
            </div>
</div>

app/views/users/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">

    <li class="nav-item">
      <% if logged_in? %>
        <div class="p-2 "><span>Welcome, <%= current_user.name %>!</span></div>
      <% end %>
    </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "My events", users_show_path %></div>
      </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "Attendees", events_show_path %></div>
      </li>

      <li class="nav-item">
          <div class="p-2 "><%= link_to "Index", events_index_path %></div>
      </li>

      <li class="nav-item">
        <div class="p-2 "><%= link_to "Create", new_event_url %></div>
      </li>

      <li class="nav-item">
      <% if logged_in? %>
      <div class="p-2 "><%= link_to "Log out", logout_path %></div>
      <% end %>
    </li>
    </ul>
  </div>
</nav>

app/views/users/index.html.erb
<% provide(:title, @user.name) %>
<%= render 'navbar', user: @user, event: @event %>
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <% if !logged_in? %>
      <%= link_to "Log in", users_new_path %>
    <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Upcoming Events</h2>
        <% if @events.empty? %>
          <span>No events created (yet)</span>
        <% else %>
          <% @events.each do |event| %>
              <tr>
                <td><%= link_to event.location, event_path(event) %></td></br>
                <td><%= event.date %></td></br>
              <% end %>
            </tr>   
        <% end %>


      </div>
    </div>
  </div>
</div>


<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Do you want to create an event?</h2>
        <%= link_to "Create Event", new_event_url %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if logged_in? %>
  <div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">No Events</h2>
        
        <span>There aren't any created events yet,</span>
        <%= link_to "Create one!", new_event_url %>
        <div class="p-2 "><%= link_to "Log out", logout_path %></div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= render 'navbar', user: @user, event: @event %>
<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <% if !logged_in? %>
      <%= link_to "Log in", users_new_path %>
    <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
      <h2 class="title is-2 is-spaced has-text-centered">My Events</h2>    
      <% if current_user.events.empty? %>
        <span>You haven't created any event yet,</span>
        <%= link_to "Create one!", new_event_url %>
      <% else %>
        <% @events.each do |event| %>
          <tr>
            <% if event.creator_id == session[:user_id] %>
              <td><%= link_to event.location, event_path(event) %></td></br>
              <td><%= event.date %></td></br>
              
              <%= form_with model: @event_invitation do |f| %>
                <%= f.collection_select :user_id, User.all,:id , :name, include_blank: true  %>     
                <%= f.hidden_field :event_id, value: event.id %>           
                <%= f.submit "Invite!", class: "button s-large is-fullwidth btn btn-large btn-primary" %>
            <% end %>
            
            <% end %>
          </tr>   
        <% end %>
      <% end %>
      </div>
    </div>
  </div>
</div>



<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">
        <h3 class="title is-2 is-spaced has-text-centered">Attendees List</h3>
        <% if @event.nil? %>
          <span>Nobody has confirmed yet, be the first one!</span>
        <% else %>
          <span>Number of attendees: <%= User.find(@event.attendees.map { |enr| enr.id }).count %></span></br>
          <%= render 'list', event: @event %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Previous Events</h2>
        <% if @events.past.empty? %>
        <span> There are no past events </span>
        <% else %>
          <% @events.past.each do |event| %>
            <tr>
                <td><%=link_to event.location, event_path(event) %></td></br>
                <td><%= event.date %></td></br>
            </tr>
          <% end %>   
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="section">
  <div class="container">
	<div class="columns is-centered">
      <div class="column is-4">
        <h2 class="title is-2 is-spaced has-text-centered">Upcoming Events</h2>
        <% @events.upcoming.each do |event| %>
          <tr>
              <td><%=link_to event.location, event_path(event) %></td></br>
              <td><%= event.date %></td></br>
          </tr>   
        <% end %>
      </div>
    </div>
  </div>
</div>